#!/bin/sh
# generate-reference.sh — regenerate the Reference MDX pages from a built wxctl binary.
#
# Usage:
#   WXCTL_BIN=/path/to/wxctl ./scripts/generate-reference.sh    # explicit binary
#   ./scripts/generate-reference.sh                              # uses `wxctl` on PATH
#
# Run from the wxctl-docs-private repo root. Writes reference/commands.mdx and
# reference/resources.mdx. Commit the result; the public docs repo has no CI to
# regenerate. See README.md "Reference generation".
set -eu

# Locate the binary: WXCTL_BIN override, else `wxctl` on PATH.
WXCTL="${WXCTL_BIN:-wxctl}"
if ! command -v "$WXCTL" >/dev/null 2>&1; then
  echo "error: wxctl binary not found. Build it (cargo build --release) and set WXCTL_BIN=/path/to/wxctl, or put wxctl on PATH." >&2
  exit 1
fi

# Resolve output dir relative to this script so it works from any CWD.
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
OUT_DIR="$SCRIPT_DIR/../reference"
mkdir -p "$OUT_DIR"

VERSION=$("$WXCTL" --version 2>/dev/null || echo "wxctl")
BANNER="{/* Generated by scripts/generate-reference.sh from $VERSION — do not hand-edit. Re-run the script to regenerate. */}"

# The 8 visible commands, in workflow order. Hidden commands (runs/debug/
# compose/profile/mcp) are intentionally excluded.
CMDS="init validate plan apply test destroy resources explain"

# ---- reference/commands.mdx ----
{
  printf '%s\n' '---'
  printf '%s\n' 'title: "Commands"'
  printf '%s\n' 'description: "The wxctl commands, their flags, and usage examples — generated from the CLI."'
  printf '%s\n' '---'
  printf '\n%s\n\n' "$BANNER"
  printf '%s\n' 'These are the commands `wxctl` exposes. Each block is the live `--help` output for this build.'
  printf '\n%s\n\n' 'The everyday workflow runs them in order: `init` → `validate` → `plan` → `apply` → `test` → `destroy`.'
  printf '%s\n' '## Global flags'
  printf '\n%s\n' '| Flag | Description |'
  printf '%s\n' '|---|---|'
  printf '%s\n' '| `-p, --profile <NAME>` | Configuration profile name (default `default`). |'
  printf '%s\n' '| `--profile-path <PATH>` | Path to a custom profile configuration file. |'
  printf '%s\n' '| `--full-trace` | Capture full-fidelity run records (also via `WXCTL_FULL_TRACE=1`). |'
  printf '\n%s\n' 'All three are global and accepted on every command. `-f, --filename` is repeatable on the file-taking commands.'
  printf '\n'
  for c in $CMDS; do
    printf '## `wxctl %s`\n\n' "$c"
    printf '```text\n'
    "$WXCTL" "$c" --help
    printf '```\n\n'
  done
  printf '%s\n' '## Other commands'
  printf '\n%s\n' '`wxctl` also ships hidden subcommands used internally by LLM-driven configuration pipelines. They are not part of the supported user-facing surface and are omitted here.'
} > "$OUT_DIR/commands.mdx"

# ---- reference/resources.mdx ----
{
  printf '%s\n' '---'
  printf '%s\n' 'title: "Resource kinds"'
  printf '%s\n' 'description: "Every resource kind wxctl supports, by product and service — generated from the CLI."'
  printf '%s\n' '---'
  printf '\n%s\n\n' "$BANNER"
  printf '%s\n' 'wxctl supports the resource kinds below. The table is generated from `wxctl resources -o markdown` for this build, so it always matches the binary.'
  printf '\n%s\n\n' '`DEPLOYMENT` shows where each kind is available — `saas`, `software`, or both.'
  printf '%s\n' '## Supported kinds'
  printf '\n'
  "$WXCTL" resources -o markdown
  printf '\n%s\n' '## Listing kinds yourself'
  printf '\n%s\n\n' 'Run `wxctl resources` to print the same catalog from your own build, with filters:'
  printf '```bash\n'
  printf '%s\n' 'wxctl resources                          # all supported kinds'
  printf '%s\n' 'wxctl resources --service watsonx_data   # filter to one service'
  printf '%s\n' 'wxctl resources --deployment software    # kinds available on Software'
  printf '%s\n' 'wxctl resources -o json                  # machine-readable output'
  printf '```\n'
  printf '\n%s\n' '## Inspecting one kind'
  printf '\n%s\n\n' 'Use `wxctl explain <kind>` to see a kind'"'"'s fields, dependencies, endpoints, and authoring notes:'
  printf '```bash\n'
  printf '%s\n' 'wxctl explain agent          # fields + dependencies for the agent kind'
  printf '%s\n' 'wxctl explain presto_engine  # any kind from the table above'
  printf '```\n'
  printf '\n%s\n' 'The output lists required vs optional fields, which fields accept `${kind.ref_name}` references, the REST endpoints wxctl calls, and authoring rules for the YAML envelope.'
} > "$OUT_DIR/resources.mdx"

echo "Wrote $OUT_DIR/commands.mdx and $OUT_DIR/resources.mdx" >&2
